export const UPDATE_CITIZEN = 'UPDATE_CITIZEN'
export const DELETE_CITIZEN = 'DELETE_CITIZEN'
export const FETCH_ALL_CITIZENS = 'FETCH_ALL_CITIZENS'
export const FETCH_CITIZEN_BY_SEARCH = 'FETCH_CITIZEN_BY_SEARCH'
export const FETCH_CITIZEN = 'FETCH_CITIZEN'
export const END_LOADING = 'END_LOADING'
export const START_LOADING = 'START_LOADING'
export const FETCH_BY_NIC = 'FETCH_BY_NIC'
export const FETCH_BY_CITIZEN_NAME = 'FETCH_BY_CITIZEN_NAME'

export const AUTH = 'AUTH'
export const LOGOUT_CITIZEN = 'LOGOUT_CITIZEN'
export const GET_CITIZEN = 'GET_CITIZEN'

// OFFICERS
export const AUTH_OFFICER = 'AUTH_OFFICER'
export const LOGOUT_OFFICER = 'LOGOUT_OFFICER'
export const GET_OFFICER = 'GET_OFFICER'

// COMPANIES
export const UPDATE_COMPANIES = 'UPDATE_COMPANIES'
export const DELETE_COMPANIES = 'DELETE_COMPANIES'
export const FETCH_ALL_COMPANIES = 'FETCH_ALL_COMPANIES'
export const FETCH_COMPANY = 'FETCH_COMPANY'
export const FETCH_COMPANIES_BY_NAME = 'FETCH_COMPANIES_BY_NAME'
export const FETCH_ALL_COMPANIES_BY_FIELD = 'FETCH_ALL_COMPANIES_BY_FIELD'
export const LOGOUT_COMPANY = 'LOGOUT_COMPANY'
export const AUTH_COMPANY = 'AUTH_COMPANY'
export const GET_COMPANY = 'GET_COMPANY'

// COMPLAINS
export const GET_COMPLAINS = 'GET_COMPLAINS'
export const CREATE_COMPLAINS = 'CREATE_COMPLAINS'
